name: SSH package

on: 
  push:
    paths-ignore:
      - '.github/**'
    branches: 
      - master

jobs:
  job1:
    name: Run Job2 Action
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@master"
      - name: "TODO-2-GH-Issue"
        uses: "Jamminroot/todo-2-gh-issue@1.1.5"
        with:
          TOKEN: ${{ secrets.GITHUBTOKEN }}
          TODO_PATTERN: "(?<=\\@todo[ :]).+"
          GH_LABEL: "TODO"
          TRIM: ",: \""
          TIMEOUT: 1000
          LINES_BEFORE: 2
          LINES_AFTER: 5
          IGNORED_LINES_LENGTH: 255
        id: "todo"
